//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musician
    {
        public int MusicianID { get; set; }
        public int ArtistID { get; set; }
        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string Role { get; set; }

        public virtual Artist Artist { get; set; }
    }
}
