//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        public int RatingID { get; set; }
        public int UserID { get; set; }
        public int AlbumID { get; set; }
        public int Rating1 { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:g}")]
        public System.DateTime Date { get; set; } = DateTime.Now;

        public virtual Album Album { get; set; }
        public virtual User User { get; set; }
    }
}
