//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Track
    {
        public int TrackID { get; set; }
        [Required(ErrorMessage = "Pole jest wymagane.")]
        public int Number { get; set; }
        [Required(ErrorMessage = "Pole jest wymagane.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Pole jest wymagane.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:mm\\:ss}")]
        public Nullable<System.TimeSpan> Length { get; set; }
        public int AlbumID { get; set; }

        public virtual Album Album { get; set; }
    }
}
